version: '3'
services:
  test-app-jdk8:
    image: "test-app-jdk8"
    container_name: test-app-jdk8
  test-app-jdk11:
    image: "test-app-jdk11"
    container_name: test-app-jdk11
  haproxy:
    image: "haproxy:1.7"
    depends_on:
    - "test-app-jdk8"
    - "test-app-jdk11"
    ports:
    - "8080:8080"
    volumes:
    - ./haproxy:/usr/local/etc/haproxy
    container_name: haproxy
  prometheus:
    depends_on:
    - "test-app-jdk8"
    - "test-app-jdk11"
    image: "prom/prometheus"
    ports:
    - "9090:9090"
    volumes:
     - ./prom-jdks.yml:/etc/prometheus/prometheus.yml
    command: "--config.file=/etc/prometheus/prometheus.yml --web.enable-admin-api"
    container_name: prometheus
  grafana:
     image: "grafana/grafana"
     ports:
     - "3000:3000"
     container_name: grafana
